<?php echo $this->headScript()->appendFile($this->assetUrl('js/hide-properties.js', 'HideProperties')); ?>
<?php echo $this->headLink()->appendStylesheet($this->assetUrl('css/hide-properties.css', 'HideProperties')); ?>
<p><?php echo $this->translate('Properties selected here will be hidden from display on all resources. Add properties from the sidebar to the right.'); ?>
</p>
<div class="field">
    <div class="field-meta">
        <label for="admin_show_all"><?= $this->translate('Show all properties on admin') ?></label>
    </div>
    <div class="inputs">
        <input type="hidden" name="admin_show_all" value="0">
        <input type="checkbox" name="admin_show_all" id="admin_show_all" value="1"<?= $this->adminShowAll ? ' checked' : '' ?>>
    </div>
</div>
<div id="hide-properties-list" data-hidden-properties="<?php echo $this->escapeHtml(json_encode($this->hiddenProperties)); ?>">
</div>
<input type="hidden" name="ignore">

<?php echo $this->propertySelector(); ?>
